services:
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: chefgpt
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: chefgpt
      INIT_WAIT_SEC: 3
    volumes:
      - chefgpt:/data/db
    ports:
      - 27017:27017

volumes:
  chefgpt:
